In [1]:
import numpy as np
import cv2
import os
from PIL import Image

In [4]:
## Hello, world ##

# Take in a photo, identify face within it, export with a rectangle

detector = cv2.CascadeClassifier('haarcascades/haarcascade_frontalface_default.xml')
image = cv2.imread('images/screen1.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
faces = detector.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(255,255,255),2)

cv2.imwrite('images/screen1_identified.png', image)

True

In [64]:
## Build recognizer ##
# Pre-requisite: Dataset of labelled images

recognizer = cv2.createLBPHFaceRecognizer()
names = ["trump", "cruz", "shkreli"]

imagePaths = []

for name in names:
    path = 'images/'+name
    imagePaths.extend([os.path.join(path, f) for f in os.listdir(path)])
    if 'images/'+name+'/.DS_Store' in imagePaths:
        imagePaths.remove('images/'+name+'/.DS_Store')
    
print imagePaths
    
def getImagesAndLabels():
    # create empty face list
    faceSamples = []
    # create empty ID list
    photoids = []
    # now loop through all the image paths and load the ids and the images
    for imagePath in imagePaths:
        # load the image and convert it to gray scale
        pilImage = Image.open(imagePath).convert('L')
        # now we convert the PIL image into numpy array
        imageNp = np.array(pilImage, 'uint8')
        # get the id from the image
        photoid = int(contestants.index(imagePath.split("/")[1]))
        # extract the face from the training image sample
        faces = detector.detectMultiScale(imageNp)
        # if a face is there then append that in the list as well as Id of it
        for (x,y,w,h) in faces:
            faceSamples.append(imageNp[y:y+h,x:x+w])
            photoids.append(photoid)
    return faceSamples, photoids

faces, photoids = getImagesAndLabels()
recognizer.train(faces, np.array(photoids))
recognizer.save('trainer/trainer.yml')

['images/vanessa/Screen Shot 2017-02-10 at 3.57.27 PM.png', 'images/vanessa/Screen Shot 2017-02-10 at 3.57.34 PM.png', 'images/vanessa/Screen Shot 2017-02-10 at 3.57.39 PM.png', 'images/vanessa/Screen Shot 2017-02-10 at 3.57.47 PM.png', 'images/vanessa/Screen Shot 2017-02-10 at 3.57.59 PM.png', 'images/vanessa/Screen Shot 2017-02-10 at 9.55.28 AM.png', 'images/vanessa/screen1.png', 'images/rachel/frame1.png', 'images/rachel/frame2.png', 'images/rachel/frame3.png', 'images/rachel/frame4.png', 'images/corinne/frame000.jpg', 'images/corinne/frame10470.jpg', 'images/corinne/frame10500.jpg', 'images/corinne/frame10530.jpg', 'images/corinne/frame12840.jpg', 'images/corinne/frame12870.jpg', 'images/corinne/frame14880.jpg', 'images/corinne/frame14910.jpg', 'images/corinne/frame14940.jpg', 'images/corinne/frame14970.jpg', 'images/corinne/frame600.jpg', 'images/corinne/frame9630.jpg', 'images/corinne/frame9780.jpg', 'images/corinne/frame9810.jpg', 'images/corinne/frame9840.jpg', 'images/corinne/

In [65]:
# recognizer.load('trainer/trainer.yml')

# font = cv2.cv.InitFont(cv2.cv.CV_FONT_HERSHEY_COMPLEX_SMALL, 5, 1, 0, 4)
# path = "images/training"
# imagePaths = [os.path.join(path, f) for f in os.listdir(path)] 
# # now loop through all the image paths and load the ids and the images
# for imagePath in imagePaths:
#     image = cv2.imread(imagePath)
#     gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#     faces = detector.detectMultiScale(gray, 1.3, 5)
#     print faces
#     for (x, y, w, h) in faces:
#         cv2.rectangle(image, (x, y), (x+w, y+h), (0, 0, 255), 2)
#         id, conf = recognizer.predict(gray[y:y+h, x:x+w])
#         if id in range(0, 6):
#             id = contestants[id]
#         cv2.cv.PutText(cv2.cv.fromarray(image),  str(id), (x,y+h), font, 255)
# #             print imagePath
#     outputpath = 'images/2104_id/' + imagePath.split("/")[-1][5:-4] + '_identified.png'
#     print outputpath
#     cv2.imwrite(outputpath, image)

()
images/2104_id/0_identified.png
()
images/2104_id/10020_identified.png
[[577 383 231 231]]
images/2104_id/10050_identified.png
()
images/2104_id/10080_identified.png
()
images/2104_id/10110_identified.png
()
images/2104_id/10140_identified.png
()
images/2104_id/10170_identified.png
[[375 492  79  79]]
images/2104_id/1020_identified.png
[[561 377 243 243]]
images/2104_id/10200_identified.png
()
images/2104_id/10230_identified.png
()
images/2104_id/10260_identified.png
()
images/2104_id/10290_identified.png
[[570 337 234 234]]
images/2104_id/10320_identified.png
()
images/2104_id/10350_identified.png
[[547 390 197 197]]
images/2104_id/10380_identified.png
()
images/2104_id/10410_identified.png
[[576 329 225 225]]
images/2104_id/10440_identified.png
[[573 333 229 229]]
images/2104_id/10470_identified.png
()
images/2104_id/1050_identified.png
[[605 338 230 230]]
images/2104_id/10500_identified.png
[[601 346 228 228]]
images/2104_id/10530_identified.png
()
images/2104_id/10560_identified

KeyboardInterrupt: 